{
    "token": 'iOJpzJlOafRnRCFmhnDptlHHFDzzxiGq-q_2jFhiC0lXroBoOmNustKN0KNC_GJzO-mSC-7sK4nlOUAiTyGB_TgxsJ7FKOar3Y9Ygfl_5Jku540xW6KpTWLv',
    "study_id": '670798ee432e84b4f5b09c4e',
    "max_concurrent_sessions": 30,
    "workload_checker_period": 60
}