{
    "token": 'iOJpzJlOafRnRCFmhnDptlHHFDzzxiGq-q_2jFhiC0lXroBoOmNustKN0KNC_GJzO-mSC-7sK4nlOUAiTyGB_TgxsJ7FKOar3Y9Ygfl_5Jku540xW6KpTWLv',
    "study_id": '6707e6e1de911719ec2e37ac',
    "max_concurrent_sessions": 30,
    "workload_checker_period": 60
}